# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: test
    name: go test
    entry: go test ./... -v
    language: system
    types: [go]
    pass_filenames: false
  - id: tailwind
    name: Generate tailwind CSS
    language: system
    entry: tailwindcss -i config.css -o http/static/style.css
    files: ^html/.*
    pass_filenames: false
- repo: https://github.com/golangci/golangci-lint
  rev: v2.11.4
  hooks:
  - id: golangci-lint-config-verify
  - id: golangci-lint-full
  - id: golangci-lint-fmt
